/*
@license
dhtmlxScheduler.Net v.3.3.2 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){!function(){var t=e.createTimelineView;e.createTimelineView=function(a){function n(){var t=new Date(e.getState().date),n=e.date[h+"_start"](t);n=e.date.date_part(n);var i=[],r=e.matrix[h];r.y_unit=i,r.order={};for(var d=0;d<a.days;d++)i.push({key:+n,label:n}),r.order[r.y_unit[d].key]=d,n=e.date.add(n,1,"day")}function i(e){var t={};for(var a in e)t[a]=e[a];return t}function r(e,t){t.setFullYear(e.getFullYear()),t.setMonth(e.getMonth()),t.setDate(e.getDate())}function d(t){
for(var a=[],n=0;n<t.length;n++){var i=o(t[n]);if(e.isOneDayEvent(i))s(i),a.push(i);else{for(var r=new Date(Math.min(+i.end_date,+e._max_date)),d=new Date(Math.max(+i.start_date,+e._min_date)),l=[];+r>+d;){var h=o(i);h.start_date=d,h.end_date=new Date(Math.min(+c(h.start_date),+r)),d=c(d),s(h),a.push(h),l.push(h)}_(l,i)}}return a}function _(e,t){for(var a=!1,n=!1,i=0,r=e.length;r>i;i++){var d=e[i];a=+d._w_start_date==+t.start_date,n=+d._w_end_date==+t.end_date,d._no_resize_start=d._no_resize_end=!0,
a&&(d._no_resize_start=!1),n&&(d._no_resize_end=!1)}}function o(t){var a=e.getEvent(t.event_pid);return a&&a.isPrototypeOf(t)?(t=e._copy_event(t),delete t.event_length,delete t.event_pid,delete t.rec_pattern,delete t.rec_type):t=e._lame_clone(t),t}function s(t){if(!t._w_start_date||!t._w_end_date){var a=e.date,n=t._w_start_date=new Date(t.start_date),i=t._w_end_date=new Date(t.end_date);t[v]=+a.date_part(t.start_date),t._count||(t._count=1),t._sorder||(t._sorder=0);var r=i-n;t.start_date=new Date(e._min_date),
l(n,t.start_date),t.end_date=new Date(+t.start_date+r)}}function l(e,t){t.setMinutes(e.getMinutes()),t.setHours(e.getHours())}function c(t){var a=e.date.add(t,1,"day");return a=e.date.date_part(a)}if("days"!=a.render)return void t.apply(this,arguments);var h=a.name,v=a.y_property="timeline-week"+h;a.y_unit=[],a.render="bar",a.days=a.days||7,t.call(this,a),e.templates[h+"_scalex_class"]=function(){},e.templates[h+"_scaley_class"]=function(){},e.templates[h+"_scale_label"]=function(t,a,n){return e.templates.day_date(a);

},e.date[h+"_start"]=function(t){return t=e.date.week_start(t),t=e.date.add(t,a.x_step*a.x_start,a.x_unit)},e.date["add_"+h]=function(t,n){return e.date.add(t,n*a.days,"day")};var u=e._renderMatrix;e._renderMatrix=function(e,t){e&&n(),u.apply(this,arguments)};var f=e.checkCollision;e.checkCollision=function(t){if(t[v]){var t=i(t);delete t[v]}return f.apply(e,[t])},e.attachEvent("onBeforeDrag",function(t,a,n){var i=n.target||n.srcElement,r=i.className||"";if("resize"==a)e._w_line_drag_from_start=r.indexOf("dhx_event_resize_end")<0?!0:!1;
else if("move"==a&&r.indexOf("no_drag_move")>=0)return!1;return!0});var g=e["mouse_"+h];e["mouse_"+h]=function(t){var a;if(this._drag_event&&(a=this._drag_event._move_delta),void 0===a&&"move"==e._drag_mode){var n=e.matrix[this._mode],i={y:t.y};e._resolve_timeline_section(n,i);var r=t.x-n.dx,d=new Date(i.section);l(e._timeline_drag_date(n,r),d);var _=e._drag_event,o=this.getEvent(this._drag_id);_._move_delta=(o.start_date-d)/6e4,this.config.preserve_length&&t._ignores&&(_._move_delta=this._get_real_event_length(o.start_date,d,n),
_._event_length=this._get_real_event_length(o.start_date,o.end_date,n))}var t=g.apply(e,arguments);if(e._drag_mode&&"move"!=e._drag_mode){var s=null;s=new Date(e._drag_event&&e._drag_event["timeline-week"+h]?e._drag_event["timeline-week"+h]:t.section),t.y+=Math.round((s-e.date.date_part(new Date(e._min_date)))/(6e4*this.config.time_step)),"resize"==e._drag_mode&&(t.resize_from_start=e._w_line_drag_from_start)}else if(e._drag_event){var c=Math.floor(Math.abs(t.y/(1440/e.config.time_step)));c*=t.y>0?1:-1,
t.y=t.y%(1440/e.config.time_step);var v=e.date.date_part(new Date(e._min_date));v.valueOf()!=new Date(t.section).valueOf()&&(t.x=Math.floor((t.section-v)/864e5),t.x+=c)}return t},e.attachEvent("onEventCreated",function(t,a){return e._events[t]&&delete e._events[t][v],!0}),e.attachEvent("onBeforeEventChanged",function(t,a,n,i){return e._events[t.id]&&delete e._events[t.id][v],!0});var m=e.render_view_data;e.render_view_data=function(t,a){return this._mode==h&&t&&(t=d(t)),m.apply(e,[t,a])};var p=e.get_visible_events;

e.get_visible_events=function(){if(this._mode==h){e._max_date=e.date.date_part(e.date.add(e._min_date,a.days,"day"));var t=p.apply(e,arguments);return d(t)}return p.apply(e,arguments)};var x=e.addEventNow;e.addEventNow=function(t){if(e.getState().mode==h)if(t[v]){var a=new Date(t[v]);r(a,t.start_date),r(a,t.end_date)}else{var n=new Date(t.start_date);t[v]=+e.date.date_part(n)}return x.apply(e,arguments)};var y=e._render_marked_timespan;e._render_marked_timespan=function(){return e._mode!=h?y.apply(this,arguments):void 0;

}}}()});